"""add complete&delta

Revision ID: a3029840bf43
Revises: 2044c17fe15e
Create Date: 2021-03-23 13:20:00.589048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3029840bf43'
down_revision = '2044c17fe15e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
