"""add delive-time

Revision ID: 2044c17fe15e
Revises: 6ad0a6ef14c2
Create Date: 2021-03-22 19:36:13.388933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2044c17fe15e'
down_revision = '6ad0a6ef14c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('complete', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('delivery_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'delivery_time')
    op.drop_column('order', 'complete')
    # ### end Alembic commands ###
