"""add deliv to ass

Revision ID: 2448da153d1f
Revises: a3029840bf43
Create Date: 2021-03-23 13:37:02.751897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2448da153d1f'
down_revision = 'a3029840bf43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('assign_time', sa.String(length=128), nullable=True))
    op.drop_column('order', 'delivery_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('delivery_time', sa.INTEGER(), nullable=True))
    op.drop_column('order', 'assign_time')
    # ### end Alembic commands ###
