"""empty message

Revision ID: 6ad0a6ef14c2
Revises: 0bab8b363594
Create Date: 2021-03-22 11:11:35.547489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad0a6ef14c2'
down_revision = '0bab8b363594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('max_weight', sa.Integer(), nullable=True))
    op.add_column('courier', sa.Column('weight_now', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courier', 'weight_now')
    op.drop_column('courier', 'max_weight')
    # ### end Alembic commands ###
