"""add complete&delta

Revision ID: a3029840bf43
Revises: 2044c17fe15e
Create Date: 2021-03-23 13:20:00.589048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3029840bf43'
down_revision = '2044c17fe15e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('courier_type', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'courier_type')
    # ### end Alembic commands ###
