"""relationship

Revision ID: fe187b868062
Revises: 7a2a72abc471
Create Date: 2021-03-21 15:51:10.462211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe187b868062'
down_revision = '7a2a72abc471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('courier', sa.Column('type', sa.Integer(), nullable=True))
    op.drop_column('courier', 'courier_type')
    op.drop_column('courier', 'courier_id')
    op.add_column('order', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order', 'courier', ['courier_id'], ['id'])
    op.drop_column('order', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'id')
    op.drop_column('order', 'courier_id')
    op.add_column('courier', sa.Column('courier_id', sa.INTEGER(), nullable=False))
    op.add_column('courier', sa.Column('courier_type', sa.INTEGER(), nullable=True))
    op.drop_column('courier', 'type')
    op.drop_column('courier', 'id')
    # ### end Alembic commands ###
